### ISSUE TITLE
Page not found

### ISSUE THREAD

**Issue by Tearix** [Spithra/web-service#1]
Привет, приложение запустилось, но оно выдает 404 page not found
Что несколько противоречит ТЗ
![image](https://user-images.githubusercontent.com/75970449/203492503-131a821d-f682-48c5-9816-1606afa7f28e.png)

**Comment by Spithra** [comment]
Привет, исправил выделеный фрагмент, теперь работает. Просто до этого по пути localhost:8080/ ничего и небыло, весь контент находился в localhost:8080/flavors и для тестов lh:8080/post, lh:8080/put, lh:8080/delete. Сейчас исправил, все 4 запроса должны работать по пути 127.0.0.1:8080
![Скрин](https://user-images.githubusercontent.com/118829170/203496136-e6e23055-9677-45d2-80c6-d1fda34828d3.png)

![скрин2](https://user-images.githubusercontent.com/118829170/203497446-e8db493a-4100-4994-94e2-7bb2b4a2493e.png)

**Comment by Tearix** [comment]
Корень теперь отвечает, но не работает, например вот так:
```
PS C:\Users\user> curl http://127.0.0.1:8080/hello
curl : 404 page not found
```

Давай все-таки воспользуемся ginовским NoRoute

**Comment by Spithra** [comment]
Понял, сейчас посмотрю

**Comment by Spithra** [comment]
Исправил
